---
layout: cv
title: Dallin Slater
---

# Dallin Slater  

---

## Education  
### Aspiring Business Management Major
**Brigham Young University - Idaho** | Rexburg, ID  
_June 2024 - Present_

### High School Diploma  
**Hillcrest High School** | Ammon, ID  
_May 2021 - May 2021_  
- Honors Student  
- Member - National Honors Society, Ski Club  

---

## Experience  
### Secretary  
**Peak Performance Physical Therapy** | Ammon, ID  
_March 2019 - February 2020_  
- Scheduled patient visits  
- Scanned patient medical records for better accessibility and storage  
- Cleaned equipment and workspace to provide a clean environment for patients and employees  
- Worked independently and self-sufficiently  
- Greeted patients upon arrival  


### Lifeguard  
**Ammon City** | Ammon, ID  
_June 2018 - August 2018_  
- Taught children swimming lessons  
- Communicated effectively with children to improve their swimming abilities  
- Collaborated with team members to ensure patron safety  

---

## Skills & Achievements  
- Experienced with Python, Java, and lawn care  
- Selected for Squire Mentoring by the principal to mentor freshmen  
- Participated in Hillcrest Tennis Team and Hillcrest Swim Team  
- Vice President for National Youth Leadership Training (Cedar Badge) for a crew of 25+ youth; directed camp planning and implementation  
- Enjoys tennis, competitive swimming, recreational skiing, reading, card games, and drawing  
- Eagle Scout

